name: Release
on:
  release:
    types: [published]
#  push:           #TEST emulate release on push on master
#    branches:     #TEST emulate release on push on master
#      - master    #TEST emulate release on push on master
  workflow_dispatch:
  
jobs:
  build:
    env:
      CONFIGURATION: Release
      BUILDPATH: src/AspNetCore.DisplayRoutes
      NUPKGPATH: packages
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: REL_*
      run: | 
        REL_GITHUB_REF=$GITHUB_REF
        echo "REL_GITHUB_REF=$GITHUB_REF" >> $GITHUB_ENV             
        #REL_GITHUB_REF="refs/tags/v0.0.1-alpha$GITHUB_RUN_NUMBER" #TEST emulate release on push on master
        echo "REL_GITHUB_REF=$REL_GITHUB_REF" >> $GITHUB_ENV       #TEST emulate release on push on master        
        REL_VERSION="${REL_GITHUB_REF/refs\/tags\/v/}"  
        echo "REL_VERSION=$REL_VERSION" >> $GITHUB_ENV             
        REL_VERSION_ONLY=$( echo "$REL_VERSION" | cut -d\- -f1) 
        echo "REL_VERSION_ONLY=$REL_VERSION_ONLY" >> $GITHUB_ENV             
      
    - name: debug/test
      run: | 
        env
        
    - name: Build
      run: dotnet build $BUILDPATH --configuration $CONFIGURATION
  
    - name: Pack
      run: |
        CMD="dotnet pack $BUILDPATH \
        --configuration $CONFIGURATION \
        --include-symbols \
        --include-source \
        -p:IncludeSymbols=true \
        -p:SymbolPackageFormat=snupkg \
        /p:Version=$REL_VERSION \
        /p:RepositoryCommit=$GITHUB_SHA \
        /p:AssemblyVersion=$REL_VERSION_ONLY \
        /p:FileVersion=$REL_VERSION_ONLY \
        -o $NUPKGPATH"
        echo $CMD
        ${CMD}

#    - name: Publish packages to NuGet.org
#      run: |
#        dotnet nuget push $NUPKGPATH'/*.nupkg' --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_KEY}}
